name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Sonatype
      run: ./gradlew publish
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

    - name: Publish Deployment in Sonatype Central
      run: |
        curl --fail --request POST \
          --user "$CENTRAL_USERNAME:$CENTRAL_PASSWORD" \
          "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.antmedia?publishing_type=automatic"
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
